"""Initial schema

Revision ID: dba3ef618d9c
Revises: 
Create Date: 2026-03-31 12:38:17.606522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dba3ef618d9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('employee_size_range', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('trial', 'active', 'suspended', 'cancelled', name='company_status'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('leave_applied', 'leave_approved', 'leave_rejected', 'task_assigned', 'task_suggested', 'task_submitted_review', 'task_approved', 'task_sent_back', 'task_rejected', 'lead_assigned', 'project_assigned', 'follow_up_due', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_notifications_company_user', ['company_id', 'user_id'], unique=False)
        batch_op.create_index('ix_notifications_company_user_unread', ['company_id', 'user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yearly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_employees', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_id'), ['id'], unique=False)

    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'SUPPORT', name='platform_admin_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='platform_admin_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('platform_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_admins_id'), ['id'], unique=False)

    op.create_table('company_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_contacts_id'), ['id'], unique=False)

    op.create_table('company_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'feature_id', name='uq_company_features_company_feature')
    )
    with op.batch_alter_table('company_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_features_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_features_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_features_id'), ['id'], unique=False)

    op.create_table('company_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='billing_cycle'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_subscriptions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_subscriptions_plan_id'), ['plan_id'], unique=False)

    op.create_table('feature_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('page_code', sa.String(length=100), nullable=False),
    sa.Column('page_name', sa.String(length=150), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'page_code', name='uq_feature_pages_feature_code')
    )
    with op.batch_alter_table('feature_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_pages_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_pages_id'), ['id'], unique=False)

    op.create_table('platform_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['platform_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_sessions_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)

    op.create_table('roles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_roles_company_name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', name='user_status'), nullable=False),
    sa.Column('is_company_admin', sa.Boolean(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'emp_id', name='uq_users_company_emp_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index('uq_users_company_email', ['company_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))

    op.create_table('attendance',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'leave', 'half_day', name='attendance_status'), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'date', name='uq_attendance_company_user_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_attendance_company_user_date', ['company_id', 'user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_marked_by'), ['marked_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)

    op.create_table('leads',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'follow_up', 'negotiation', 'won', 'lost', name='lead_status'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_created', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_leads_company_next_follow_up_date', ['company_id', 'next_follow_up_date'], unique=False)
        batch_op.create_index('ix_leads_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('casual', 'sick', 'earned', 'unpaid', 'comp_off', name='leave_type'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_quota', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('used', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('remaining', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'leave_type', 'year', name='uq_leave_balances_company_user_type_year')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_leave_balances_company_user_type_year', ['company_id', 'user_id', 'leave_type', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_user_id'), ['user_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('casual', 'sick', 'earned', 'unpaid', 'comp_off', name='leave_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_leave_requests_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_leave_requests_company_user_applied_at', ['company_id', 'user_id', 'applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_user_id'), ['user_id'], unique=False)

    op.create_table('roles_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'feature_id', name='uq_roles_features_role_feature')
    )
    with op.batch_alter_table('roles_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_features_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_features_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_features_role_id'), ['role_id'], unique=False)

    op.create_table('teams',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='team_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_teams_company_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_teams_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_manager_id'), ['manager_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alt_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('lead_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logged_by', sa.UUID(), nullable=False),
    sa.Column('interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_interactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_interactions_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_interactions_logged_by'), ['logged_by'], unique=False)

    op.create_table('projects',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('assigned_team_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('unassigned', 'assigned', 'planned', 'in_progress', 'completed', 'on_hold', name='project_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_assigned_team_id'), ['assigned_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_projects_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_lead_id'), ['lead_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_user')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('project_planning',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('client_requirements', sa.Text(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_project_planning_project_id')
    )
    with op.batch_alter_table('project_planning', schema=None) as batch_op:
        batch_op.create_index('ix_project_planning_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_planning_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_planning_project_id'), ['project_id'], unique=False)

    op.create_table('project_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('unassigned', 'assigned', 'planned', 'in_progress', 'completed', 'on_hold', name='project_status'), nullable=True),
    sa.Column('new_status', sa.Enum('unassigned', 'assigned', 'planned', 'in_progress', 'completed', 'on_hold', name='project_status'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_logs_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index('ix_project_status_logs_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_logs_project_id'), ['project_id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending_approval', 'active', 'in_progress', 'review', 'done', 'rejected', 'blocked', name='task_status'), nullable=False),
    sa.Column('dependency_task_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dependency_task_id'], ['project_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index('ix_project_tasks_company_assigned_status', ['company_id', 'assigned_to', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_dependency_task_id'), ['dependency_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('task_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('update_type', sa.String(length=100), nullable=True),
    sa.Column('old_status', sa.Enum('pending_approval', 'active', 'in_progress', 'review', 'done', 'rejected', 'blocked', name='task_status'), nullable=True),
    sa.Column('new_status', sa.Enum('pending_approval', 'active', 'in_progress', 'review', 'done', 'rejected', 'blocked', name='task_status'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_updates_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_updates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_updates_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_updates_updated_by'), ['updated_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_updates_updated_by'))
        batch_op.drop_index(batch_op.f('ix_task_updates_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_updates_id'))
        batch_op.drop_index(batch_op.f('ix_task_updates_company_id'))

    op.drop_table('task_updates')
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_dependency_task_id'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_created_by'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_company_id'))
        batch_op.drop_index('ix_project_tasks_company_assigned_status')
        batch_op.drop_index(batch_op.f('ix_project_tasks_assigned_to'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_status_logs_id'))
        batch_op.drop_index('ix_project_status_logs_company_id')
        batch_op.drop_index(batch_op.f('ix_project_status_logs_changed_by'))

    op.drop_table('project_status_logs')
    with op.batch_alter_table('project_planning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_planning_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_planning_id'))
        batch_op.drop_index('ix_project_planning_company_id')

    op.drop_table('project_planning')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_lead_id'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index('ix_projects_company_status')
        batch_op.drop_index(batch_op.f('ix_projects_company_id'))
        batch_op.drop_index(batch_op.f('ix_projects_assigned_team_id'))

    op.drop_table('projects')
    with op.batch_alter_table('lead_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_interactions_logged_by'))
        batch_op.drop_index(batch_op.f('ix_lead_interactions_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_interactions_id'))

    op.drop_table('lead_interactions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_company_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_company_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_manager_id'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))
        batch_op.drop_index('ix_teams_company_status')
        batch_op.drop_index(batch_op.f('ix_teams_company_id'))

    op.drop_table('teams')
    with op.batch_alter_table('roles_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_features_role_id'))
        batch_op.drop_index(batch_op.f('ix_roles_features_id'))
        batch_op.drop_index(batch_op.f('ix_roles_features_feature_id'))

    op.drop_table('roles_features')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_id'))
        batch_op.drop_index('ix_leave_requests_company_user_applied_at')
        batch_op.drop_index('ix_leave_requests_company_status')
        batch_op.drop_index(batch_op.f('ix_leave_requests_company_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_user_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_id'))
        batch_op.drop_index('ix_leave_balances_company_user_type_year')
        batch_op.drop_index(batch_op.f('ix_leave_balances_company_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_created_by'))
        batch_op.drop_index('ix_leads_company_status')
        batch_op.drop_index('ix_leads_company_next_follow_up_date')
        batch_op.drop_index(batch_op.f('ix_leads_company_id'))
        batch_op.drop_index(batch_op.f('ix_leads_assigned_to'))

    op.drop_table('leads')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_marked_by'))
        batch_op.drop_index(batch_op.f('ix_attendance_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))
        batch_op.drop_index('ix_attendance_company_user_date')
        batch_op.drop_index(batch_op.f('ix_attendance_company_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_company_email', postgresql_where=sa.text('email IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.drop_index(batch_op.f('ix_roles_company_id'))

    op.drop_table('roles')
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_sessions_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_platform_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_platform_sessions_admin_id'))

    op.drop_table('platform_sessions')
    with op.batch_alter_table('feature_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_pages_id'))
        batch_op.drop_index(batch_op.f('ix_feature_pages_feature_id'))

    op.drop_table('feature_pages')
    with op.batch_alter_table('company_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_subscriptions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_company_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_company_subscriptions_company_id'))

    op.drop_table('company_subscriptions')
    with op.batch_alter_table('company_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_features_id'))
        batch_op.drop_index(batch_op.f('ix_company_features_feature_id'))
        batch_op.drop_index(batch_op.f('ix_company_features_company_id'))

    op.drop_table('company_features')
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_company_contacts_company_id'))

    op.drop_table('company_contacts')
    with op.batch_alter_table('platform_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_admins_id'))

    op.drop_table('platform_admins')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_id'))

    op.drop_table('plans')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index('ix_notifications_company_user_unread')
        batch_op.drop_index('ix_notifications_company_user')
        batch_op.drop_index(batch_op.f('ix_notifications_company_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_id'))

    op.drop_table('features')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    # ### end Alembic commands ###
